In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys,os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist
from gradient_simplenet import simpleNet
from common import functions
from common import gradient


def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1
   
def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    b = 0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y
    
def step_function(x):
    return np.array(x > 0, dtype=np.int64)
    
    
def sigmoid(x):
    return 1 / (1+np.exp(-x))
    
def relu(x):
    return np.maximum(0, x)
    
def identify_function(x):
    return x

def softmax(x):
    c = np.max(x) # オーバーフロー対策
    exp_a = np.exp(x - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    return y

# 2乗誤差
def mean_squared_error(y, t):
    return 0.5 * np.sum((y-t)**2)
    
# 交差エントロピー誤差
def cross_entorypy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    batch_size = y.shape[0]
    return -np.sum(t*np.log(y)/batch_size)
    
def numerical_diff(f, x):
    h = 1e-4
    return (f(x+1) - f(x-1)) / 2*h

# 勾配を求める
def numerical_gredient(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    for idx in range(x.size):
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x)

        x[idx] = tmp_val - h
        fxh2 = f(x)

        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val
        
    return grad
    
# 勾配降下法
def gradient_descent(f, init_x, lr = 0.01, step_num=100):
    x = init_x
    
    for i in range(step_num):
        grad = numerical_gredient(f, x)
        x -= lr * grad
    return x

def function_2(x):
    return x[0]**2 + x[1]**2

net = simpleNet()
x = np.array([0.6, 0.9])
p = net.predict(x)
t = np.array([0,0,1])
def f(W):
    return net.loss(x, t)

dW = gradient.numerical_gradient(f, net.W)
dW

[[ 0.15759391  0.2300987  -0.38769261]
 [ 0.23639087  0.34514804 -0.58153891]]


array([[ 0.20811197,  0.27826521, -0.48637718],
       [ 0.31216796,  0.41739781, -0.72956577]])